name: Waka Readme

on:
  schedule:
    # runs at 12 AM UTC (3 AM EAT)
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_LINES_OF_CODE: True
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_PROFILE_VIEWS: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROJECTS: False
